import type { SignalRule } from "./rule-engine";

export interface PackageFingerprintSpec {
  name: string;
  label: string;
  weight: number;
}

const README_TUTORIAL_PATTERNS = [
  /\bwe(?:'ll| will)\s+(?:now|first|next)\b/gi,
  /\bin this example\b/gi,
  /\blet['\u2019]s\s+(?:add|build|create|start)\b/gi,
  /\bstep\s*\d+\s*[:.]/gi,
  /\bfirst,\s+we\b/gi,
];

const AI_KEYWORD_PATTERN =
  /(copilot|cursor|claude|chatgpt|gpt-?4|gemini|generated by ai|lovable|vibecod|codex)/gi;
const AI_TOOL_CONFIG_PATTERN =
  /AGENTS\.md|CLAUDE\.md|copilot-instructions\.md|\.cursorrules|\.windsurfrules/gi;

const TW_UTILITY =
  /\b(?:bg|text|p[trblxy]?|m[trblxy]?|flex|grid|rounded|border|gap|w|h|min-[wh]|max-[wh]|shadow|ring|space-[xy]|items|justify|hover:|dark:|md:|lg:|sm:)[-:][a-z0-9/[\]#().-]+/g;

export function createPackageFingerprintRules(specs: PackageFingerprintSpec[]): SignalRule[] {
  return specs.map((spec) => ({
    id: `vibe.package.${spec.label}`,
    category: "vibe",
    label: spec.label,
    weight: spec.weight,
    match: (text, source) =>
      text.includes(`"${spec.name}`) || text.includes(spec.name)
        ? `${source} includes ${spec.label}.`
        : null,
  }));
}

export function createAiToolingRules(): SignalRule[] {
  return [
    {
      id: "ai.config_files",
      category: "ai",
      label: "AI-tooling config files",
      weight: 40,
      match: (input) => {
        const matches = input.match(AI_TOOL_CONFIG_PATTERN);
        return matches && matches.length > 0 ? `Found: ${matches.join(", ")}` : null;
      },
    },
    {
      id: "ai.commit_keywords",
      category: "ai",
      label: "AI keywords in commit messages",
      weight: 25,
      match: (input) => {
        const matches = input.match(AI_KEYWORD_PATTERN);
        return matches && matches.length > 0
          ? `Found commit keywords: ${matches.slice(0, 5).join(", ")}`
          : null;
      },
    },
    {
      id: "ai.bot_authors",
      category: "ai",
      label: "Bot / AI-tool authored commits",
      weight: 20,
      match: (input, source) =>
        /\[bot\]|copilot|lovable/i.test(input) ? `Found bot-style authors in ${source}.` : null,
    },
  ];
}

export function createReadmeHeuristicRules(): SignalRule[] {
  return [
    {
      id: "ai.tutorial_voice",
      category: "ai",
      label: "LLM-style tutorial voice",
      weight: 15,
      match: (text, source) => {
        let hits = 0;
        const samples: string[] = [];
        for (const pattern of README_TUTORIAL_PATTERNS) {
          const matches = text.match(pattern);
          if (!matches) continue;
          hits += matches.length;
          if (samples.length < 3) samples.push(matches[0]);
        }
        if (hits < 2) return null;
        return `Found ${hits} tutorial-voice phrases in ${source}: ${samples.join(", ")}`;
      },
    },
    {
      id: "ai.emoji_headers",
      category: "ai",
      label: "Emoji-decorated markdown headers",
      weight: 5,
      match: (text, source) => {
        const emojiHeader = text.match(/^#{1,3}\s+[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/gmu);
        if (!emojiHeader || emojiHeader.length < 2) return null;
        return `${emojiHeader.length} markdown headers start with emoji in ${source}.`;
      },
    },
  ];
}

export function createWebsiteHtmlRules(): SignalRule[] {
  return [
    {
      id: "vibe.tailwind_density",
      category: "vibe",
      label: "Tailwind utility class density",
      weight: 25,
      match: (text, source) => {
        const matches = text.match(TW_UTILITY);
        if (!matches || matches.length < 15) return null;
        return `~${matches.length} Tailwind-style utility classes detected in ${source}. Sample: ${matches.slice(0, 5).join(" ")}`;
      },
    },
    {
      id: "vibe.css_variables",
      category: "vibe",
      label: "Design-token CSS custom properties",
      weight: 15,
      match: (text, source) => {
        const varDefs = text.match(/--[a-z][a-z0-9-]*\s*:/gi);
        if (!varDefs || varDefs.length < 6) return null;
        return `${varDefs.length} CSS custom properties (--tokens) defined in ${source}.`;
      },
    },
    {
      id: "vibe.framework_hints",
      category: "vibe",
      label: "Modern framework fingerprints",
      weight: 10,
      match: (text) => {
        const hints: string[] = [];
        if (/tailwind/i.test(text)) hints.push("Tailwind");
        if (/_next\/static/i.test(text)) hints.push("Next.js");
        if (/\/assets\/index-[a-z0-9]+\.js/i.test(text)) hints.push("Vite");
        if (/react/i.test(text)) hints.push("React");
        return hints.length > 0 ? `Detected: ${hints.join(", ")}` : null;
      },
    },
    {
      id: "vibe.shadcn_fingerprint",
      category: "vibe",
      label: "shadcn/ui-style component fingerprints",
      weight: 15,
      match: (text) =>
        /data-slot=|data-radix-|cn\(|class="[^"]*\b(?:btn|card|input)-/i.test(text) &&
        /rounded-md|bg-primary/i.test(text)
          ? "Detected Radix data attributes + shadcn-flavored utility classes."
          : null,
    },
    {
      id: "vibe.generator_meta",
      category: "vibe",
      label: "Generator meta tag",
      weight: 5,
      match: (text) => {
        const gen = /<meta[^>]+name=["']generator["'][^>]+content=["']([^"']+)["']/i.exec(text);
        return gen ? `<meta name="generator" content="${gen[1]}">` : null;
      },
    },
    {
      id: "ai.generator_meta",
      category: "ai",
      label: "AI-tool generator meta tag",
      weight: 30,
      match: (text) => {
        const gen = /<meta[^>]+name=["']generator["'][^>]+content=["']([^"']+)["']/i.exec(text);
        if (!gen || !/lovable|v0|bolt|copilot/i.test(gen[1])) return null;
        return `Page generated by ${gen[1]}.`;
      },
    },
  ];
}

export function createStylesheetRules(sheetUrl: string): SignalRule[] {
  return [
    {
      id: `vibe.css_variables.${sheetUrl}`,
      category: "vibe",
      label: "Design-token CSS custom properties",
      weight: 15,
      match: (text, source) => {
        const varDefs = text.match(/--[a-z][a-z0-9-]*\s*:/gi);
        if (!varDefs || varDefs.length < 6) return null;
        return `${varDefs.length} CSS custom properties (--tokens) defined in ${source}.`;
      },
    },
    {
      id: `vibe.tailwind_css.${sheetUrl}`,
      category: "vibe",
      label: "Tailwind-compiled stylesheet",
      weight: 20,
      match: (text) =>
        /--tw-|tailwindcss/i.test(text)
          ? `Stylesheet ${sheetUrl} contains Tailwind runtime tokens.`
          : null,
    },
  ];
}
