import {
  type AnalysisResult,
  type Signal,
  scoreFromSignals,
  detectTailwindClassDensity,
  detectCssVariables,
} from "./signals";

async function fetchText(url: string, maxBytes = 2_000_000): Promise<string | null> {
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": "VibeDetector/1.0 (+https://lovable.dev)" },
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok) return null;
    const ct = res.headers.get("content-type") ?? "";
    if (!/text|css|html|javascript|json/i.test(ct)) return null;
    const buf = await res.arrayBuffer();
    if (buf.byteLength > maxBytes) return null;
    return new TextDecoder().decode(buf);
  } catch {
    return null;
  }
}

function extractStylesheetLinks(html: string, base: string): string[] {
  const out: string[] = [];
  const re = /<link[^>]+rel=["']?stylesheet["']?[^>]*>/gi;
  const hrefRe = /href=["']([^"']+)["']/i;
  const matches = html.match(re) ?? [];
  for (const tag of matches) {
    const h = hrefRe.exec(tag);
    if (h) {
      try {
        out.push(new URL(h[1], base).toString());
      } catch {
        // ignore
      }
    }
  }
  return out.slice(0, 2);
}

export async function analyzeWebsite(inputUrl: string): Promise<AnalysisResult> {
  const target = inputUrl;
  const html = await fetchText(inputUrl);
  if (!html) {
    return {
      target,
      kind: "website",
      vibeScore: 0,
      aiScore: 0,
      signals: [],
      error: "Could not fetch page (blocked, timed out, or not HTML).",
    };
  }

  const signals: Signal[] = [];

  const tw = detectTailwindClassDensity(html, "index.html");
  if (tw) signals.push(tw);

  const cv = detectCssVariables(html, "index.html (inline styles)");
  if (cv) signals.push(cv);

  // Framework hints from script src
  const scripts = html.match(/<script[^>]+src=["']([^"']+)["']/gi) ?? [];
  const scriptSrcs = scripts.join(" ");
  const hints: string[] = [];
  if (/tailwind/i.test(scriptSrcs) || /tailwind/i.test(html)) hints.push("Tailwind");
  if (/_next\/static/i.test(scriptSrcs)) hints.push("Next.js");
  if (/\/assets\/index-[a-z0-9]+\.js/i.test(scriptSrcs)) hints.push("Vite");
  if (/react/i.test(scriptSrcs)) hints.push("React");
  if (hints.length > 0) {
    signals.push({
      id: "vibe.framework_hints",
      category: "vibe",
      label: "Modern framework fingerprints",
      weight: Math.min(10, hints.length * 3),
      evidence: `Detected: ${hints.join(", ")}`,
    });
  }

  // shadcn-ish class fingerprints
  if (/data-slot=|data-radix-|cn\(|class="[^"]*\b(?:btn|card|input)-/i.test(html) && /rounded-md|bg-primary/i.test(html)) {
    signals.push({
      id: "vibe.shadcn_fingerprint",
      category: "vibe",
      label: "shadcn/ui-style component fingerprints",
      weight: 15,
      evidence: "Detected Radix data attributes + shadcn-flavored utility classes.",
    });
  }

  // Fetch a couple of stylesheets
  const cssLinks = extractStylesheetLinks(html, inputUrl);
  for (const link of cssLinks) {
    const css = await fetchText(link, 1_000_000);
    if (!css) continue;
    const cv2 = detectCssVariables(css, link);
    if (cv2) signals.push({ ...cv2, id: `${cv2.id}.${link}` });
    if (/--tw-|tailwindcss/i.test(css)) {
      signals.push({
        id: `vibe.tailwind_css.${link}`,
        category: "vibe",
        label: "Tailwind-compiled stylesheet",
        weight: 20,
        evidence: `Stylesheet ${link} contains Tailwind runtime tokens.`,
      });
    }
  }

  // Meta generator
  const gen = /<meta[^>]+name=["']generator["'][^>]+content=["']([^"']+)["']/i.exec(html);
  if (gen) {
    signals.push({
      id: "vibe.generator_meta",
      category: "vibe",
      label: `Generator meta tag: ${gen[1]}`,
      weight: 5,
      evidence: `<meta name="generator" content="${gen[1]}">`,
    });
    if (/lovable|v0|bolt|copilot/i.test(gen[1])) {
      signals.push({
        id: "ai.generator_meta",
        category: "ai",
        label: "AI-tool generator meta tag",
        weight: 30,
        evidence: `Page generated by ${gen[1]}.`,
      });
    }
  }

  const { vibe, ai } = scoreFromSignals(signals);
  return { target, kind: "website", vibeScore: vibe, aiScore: ai, signals };
}
